name: Compilar Tesis LaTeX

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Compilar PDF de la Tesis
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report/TFGTeXiS.tex # Ruta correcta en tu GitHub
          # Forzamos los argumentos para ignorar errores menores y registrar todo
          args: "-pdf -file-line-error -interaction=nonstopmode"

      - name: Guardar PDF o Reporte de Errores
        if: always() # Obliga a guardar los archivos creados incluso si la compilación falla
        uses: actions/upload-artifact@v4
        with:
          name: TFG-Resultado-O-Logs
          path: |
            report/TFGTeXiS.pdf
            report/TFGTeXiS.log
