name: Compilar Tesis LaTeX

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Compilar PDF de la Tesis
        uses: xu-cheng/latex-action@v3
        with:
          # Al definir el directorio de trabajo, el archivo raíz pasa a ser solo el nombre del archivo
          root_file: TFGTeXiS.tex
          working_directory: report
          args: "-pdf -file-line-error -interaction=nonstopmode"

      - name: Guardar PDF o Reporte de Errores
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TFG-Resultado-O-Logs
          path: |
            report/TFGTeXiS.pdf
            report/TFGTeXiS.log
